name: DailyWhiskers
options:
  bundleIdPrefix: com.ken
  deploymentTarget:
    iOS: "17.0"
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.0.0
targets:
  DailyWhiskers:
    type: application
    platform: iOS
    sources:
      - path: DailyWhiskers
        excludes:
          - README.md
          - Resources
          - Assets.xcassets
      - path: DailyWhiskers/Resources
        buildPhase: resources
      - path: DailyWhiskers/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.example.kenwidemon.dailywhiskers
        PRODUCT_NAME: DailyWhiskers
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_CFBundleDisplayName: Daily Whiskers
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDefault
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        GENERATE_INFOPLIST_FILE: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: Firebase
        product: FirebaseCore
      - package: Firebase
        product: FirebaseAuth
    preBuildScripts: []
    postCompileScripts: []
